AsahiLinux/asahi-scripts

dracut/10-asahi.conf

Add a dracut config equivalent to the initcpio one.

Add dracut config for Fedora

---

Makefile

- On Fedora we don't need first-boot and update-grub, so gate them out
- Condizionalize binaries path so we can install them in sbin
- Add a clean target

Various makefile fixes for Fedora

---

asahi-fwextract

Can't quote here as it impedes globbing, causing the move to fail.

asahi-fwextract: fix overzealous quoting

---

dracut/modules.d/99asahi-firmware/load-asahi-firmware.sh

Not sure there's if there's a good reason to leave the esp persistently mounted here for the duration of the boot session. 
Other commands/functions that mount the esp such update-m1n1 will unmount the esp once they've completed.

umount esp upon completion

---

dracut/modules.d/99asahi-firmware/module-setup.sh

Required when the ESP is not mounted for example due to booting an USB image to encrypt the rootfs. `dracut --force` will in that situation not include vfat in the initramfs resulting in missing firmware when using that initramfs.

dracut: Add vfat as explicit dependency for asahi-firmware

---

asahi-diagnose

users were explicitly warned not to enable speakers early. these warnings were often. check for telltale signs that they hacked their way to enabled speakers despite this, and impolitely warn them that they will not receive support until they undo any early adopter hacks detected by this script.

asahi-diagnose: add checks for speaker early adopters

---

asahi-diagnose

Fixes: b17fd99 ("asahi-diagnose: add checks for speaker early adopters")

asahi-diagnose: Fix typo in audio checks

---

update-grub

It looks like this is the official way to create a new environment file. Interestingly that will initialize the buffer to all `0x23`. Filling it with `0x00` gives me `error: invalid environment file` at boot on Ubuntu.
The Arch wiki mentions `grub-editenv` create at https://wiki.archlinux.org/title/GRUB so I suppose it is also a good idea to use it there.

Use grub-editenv to create grub environment file.

---

functions.sh

The /proc/mount file is a space-separated table of all devices mounted. The current implementation only greps for a matching pattern without taking this into account. This may cause a misreading of /proc/mount when, say, the ESP was mounted at /efi (AOSC OS default).
For instance:
```
$ grep /efi /proc/mounts 
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
systemd-1 /efi autofs rw,relatime,fd=50,pgrp=1,timeout=120,minproto=5,maxproto=5,direct,pipe_ino=21868 0 0
```
Also match the spaces on either end of the mount path to avoid this issue.

functions.sh: be more precise while reading /proc/mount

---

asahi-diagnose

Wireplumber saves the UCM profile only change to it's state dir. Use "Default" as fallback when the misses profile information and do not warn about this state.

diagnose: Avoid warning on absent ucm profile state

---

dracut/modules.d/99asahi-firmware/module-setup.sh

Missing grep in the initramfs was observed with dracut on gentoo.

dracut: Install grep, mkdir as functions.sh deps

---

dracut/dracut.conf.d/10-asahi.conf

Fixes USB support in the initramfs by reverting the unintentional omission of apple-dart.ko, apple-rtkit-helper.ko,
spmi-apple-controller.ko and dwc3-of-simple.ko from the initramfs. Due to the missing dart module lot's of other HW was unusable in the initramfs as well.
Does not fix the late probing of the rtc-macsmc modfule.
The upstream module name for the i2c blocks is i2c-pasemi-platform. Although dracut includes the module already it on its own it still causes problems. Dracut seems to ignore all other modules when it can't find one of the entries in the 'add_drivers' variable.

dracut: conf: Fix i2c module name

---

Makefile
dracut/dracut.conf.d/10-asahi.conf
dracut/modules.d/91kernel-modules-asahi/module-setup.sh

The config based kernel module handling unfortunately fails with missing drivers as the handling of `add_drivers` gives up on the first missing kernel module, prints an error message but carries on to create a initramfs with missing modules.
Use our own module to call `instmod` without "-c" to avoid checks.

dracut: Add module for asahio specific kernel modules

---

dracut/dracut.conf.d/10-asahi-noextgpu.conf

Decreases initramfs size from 142M to 80M on Fedora-Asahi-Remix.

dracut: omit AMD/Nvidia GPU drivers and firmwares

---

dracut/modules.d/99asahi-dev-modules/install-asahi-dev-modules.sh
dracut/modules.d/99asahi-dev-modules/link-asahi-dev-modules.sh
dracut/modules.d/99asahi-dev-modules/module-setup.sh

This module makes modules of a development kernel blended into the initrd at "/$(uname -r) available in the initrd and root fs.
This depends on a writable root fs mount or an existing /sysroot/lib/modules/$(uname -r) directory. The script mounts a tmpfs and copies the modules into it.
The cpio archive can be created during the kernel build with
```
make dir-pkg && \
usr/gen_initramfs.sh -o initramfs_modules.cpio -u squash -g squash tar-install/lib/modules && \
gzip -f --fast initramfs_modules.cpio
```
usr/gen_initramfs.sh does not work with out of tree build. A simple workaround is to copy usr/gen_initramfs from kernel build dir to usr/ in the kernel source dir.
The regular initramfs, a firmware.cpio.gz and initramfs_modules.cpio.gz can then be concatenated and used as initramfs for …

dracut: Add asahi-dev-modules dracut module

---

Makefile
macsmc-battery/systemd/macsmc-battery-charge-control-end-threshold.path
macsmc-battery/systemd/macsmc-battery-charge-control-end-threshold.service
macsmc-battery/udev/93-macsmc-battery-charge-control.rules

Add udev rule and systemd units to store charge_control_end_threshold so it can be restored on the next boot.

macsmc-battery: persistent charge_control_end_threshold

---

asahi-diagnose

Part of `asahi-diagnose` fails to run on Debian because `==` is not posix compliant and undefined in `dash` (~ `/bin/sh`). This MR fixes this.
For the record, AFAICS there's another source of posix non-compliance in `asahi-diagnose`, that being `local profile_config=...` in `check_macaudio_profile()` (`local` is not defined in posix). `local` is defined in `dash` though, so I'm not changing that in this MR. If you would like me to change it nonetheless I can do it in another MR.

asahi-diagnose: use posix-compliant equality comparison

---

Makefile

This bit causes systemd to emit the following warning: "Configuration file /usr/lib/udev/rules.d/93-macsmc-battery-charge-control.rules is marked executable. Please remove executable permission bits. Proceeding anyway."

Remove executable bit from the rules file.

---

update-m1n1

The glob pattern for the Apple silicon devicetrees is OS dependent. Do not pretend that's possible to provide a default value and instead error out if it is unset.
Motivated by the addition of devicetrees for non macOS devices which should be excluded from the 2nd stage m1n1 binary.

update-m1n1: Drop arch specific default DTBS glob pattern

---

Makefile

In 4ffde284be81a776b9ba01c6a50dacbee10e1dcc you just added this to the fedora flavor, but this will work on arch also.
@jannau If you could merge this that would be great, thanks!

`install-arch should` also `install-macsmc-battery`

---

initcpio/install/asahi

Just like f444f0aaa7841c02820c67569beff509d5850908
@jannau Can you please clarify my comment here https://github.com/AsahiLinux/asahi-scripts/commit/4acd310cd8c394f9ec2e7e7506d89b7bb3c3ca39#r150493522 - do we need `i2c-apple` here still also? Thanks!
fyi, on alarm:
```
$ modinfo i2c-apple
modinfo: ERROR: Module i2c-apple not found.
$ modinfo i2c-pasemi-platform
name:           i2c_pasemi_platform
filename:       (builtin)
description:    Apple/PASemi SMBus platform driver
author:         Sven Peter <sven@svenpeter.dev>
license:        GPL
file:           drivers/i2c/busses/i2c-pasemi-platform
```

Changed `i2c-apple` to `i2c-pasemi-platform` for initcpio

---

asahi-diagnose

The asahi-diagnose script prints a link to the old GitHub wiki. Replace it with a link to the new documentation site.

Update documentation link in asahi-diagnose

---

update-m1n1

Mitigations option was recently added to m1n1. This change allows the update-m1n1 script to read it. Currently, it only reads chosen and display options.

update-m1n1: enable/read mitigations option

---

update-m1n1

Uses `sha512sum` instead of `cmp` to avoid a dependency on diffutils.

update-m1n1: clobber boot.bin.old only if boot.bin changes

---

macsmc-battery/systemd/macsmc-battery-charge-control-end-threshold.service

The current logic works, but results in SELinux AVCs because the default policy doesn't allow PID 1 to write out to arbitrary paths in /etc. Change this to do the write within the service itself instead, which should be allowed.
Fixes: #59

macsmc-battery: write out the config in the service itself

---

update-m1n1

Previously there was a moment where there where no boot.bin in place. By instead copying the backup and then overwriting boot.bin using mv -f, the replacement should be atomic.

update-m1n1: make boot.bin replacement atomic

---

dracut/modules.d/91kernel-modules-asahi/module-setup.sh

The SPMI nvmem support was merged as apple_spmi_nvmem for v6.16 and Asahi's v6.15 based downstream tree pick those patches up. Add the module the dracut config to ensure it ends up in the initramfs. Keep the old modules until v6.16++ is released to ensure compatibility with older kernels for a while.

dracut: Add apple_spmi_nvmem module

---

asahi-diagnose

The quirks were upstreamed in 6.16 and are not enabled by a kernel parameter anymore. Because of left-over checks, asahi-diagnose tells users 'Your audio configuration is in an invalid state', which is not true.
This is a hard removal of the checks. As an alternative you may want to simply neutralize them (or make them conditional on the kernel version) while some people can still be expected to be on < 6.16, or maybe it's not worth it and they can already go away. Your decision.
Cheers!

asahi-diagnose: drop the tas2764 quirk checks
